public class CreditCard {
    public Credit_Card__c creditCard;
    
    /*public void insertCreditCard(String creditCardInput, Decimal transactionChargeInput, 
	Decimal monthlyFeeInput, Decimal cCardLimitInput){
	creditCard = new Credit_Card__c();
	this.creditCard.Credit_Card__c = creditCardInput;
	this.creditCard.Transaction_Charge__c = transactionChargeInput;
	this.creditCard.Monthly_Card_Fees__c = monthlyFeeInput;
	this.creditCard.Credit_Card_Limit__c = cCardLimitInput;
	INSERT this.creditCard;
	}*/
    
    
}